from Validation.validation import validation
import pymysql
class Db:

    def __init__(self):
        self.db = pymysql.connect('localhost', 'root', '', 'user_reg')
        self.x = self.db.cursor()
        self.x.execute("USE user_reg")

    def create(self):
        self.obj = validation()
        self.a = self.obj.id()
        self.b = self.obj.username()
        self.c = self.obj.password()
        self.d = self.obj.Phone()
        self.mail = self.obj.Email()
        try:
            self.x.execute(
                "CREATE TABLE signup(Id varchar(30) PRIMARY KEY, Name varchar(20), password varchar(20), Mobile varchar(20), Email_Address varchar(20))")
        except Exception as e:
            print(f"error is occurred {e}")

    def insert(self):
        try:
            self.x.execute("INSERT INTO signup(Id, Name, password, Mobile, Email_Address) VALUES ('%s', '%s', '%s', "
                           "'%s', '%s')" % (self.a, self.b, self.c, self.d, self.mail))
            self.db.commit()
        except Exception as e:
            print(e)
        self.db.close()

    def select(self, x, y) -> object:
        self.x.execute(
            'select * from signup where Email_Address="%s" AND password="%s"' % (x, y))
        self.r = self.x.fetchone()
        return self.r


if __name__ == '__main__':
    obj1 = Db()
    obj1.create()
    obj1.insert()
